# This is a basic workflow to help you get started with Actions

name: Publish BOM to Exchange

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  publish-bom:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.4.0
        with:
          java-version: 11
          settings-servers: |
            [{
                "id": "anypoint-exchange-v2",
                "username": "~~~Client~~~",
                "password": "${{ secrets.CA_CLIENT_ID }}~?~${{ secrets.CA_CLIENT_SECRET }}"
            },
            {
                "id": "mulesoft-releases-ee",
                "username": "${{ secrets.RELEASES_EE_USERNAME }}",
                "password": "${{ secrets.RELEASES_EE_PASSWORD }}"
            }]
          
      - run: cat ~/.m2/settings.xml
      
      - run: cd bom && mvn clean deploy
